# Generated by Django 5.0.6 on 2024-06-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='firstapp.customer')),
            ],
        ),
    ]
